name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:     
      FLOW_TARGET_VERSION: 6.3
      FLOW_CONTEXT: Testing
      FLOW_FOLDER: ../flow-base-distribution

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update Composer
      run: |
        sudo composer self-update
        composer --version

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.composer/cache
        key: dependencies-composer-${{ hashFiles('composer.json') }}

    - name: Prepare Flow distribution
      run: |
        git clone https://github.com/neos/flow-base-distribution.git -b ${FLOW_TARGET_VERSION} ${FLOW_FOLDER}
        cd ${FLOW_FOLDER}
        composer install --prefer-dist --no-interaction --no-progress

    - name: Install package
      run: |
        cd ${FLOW_FOLDER} 
        composer config repositories.restapi path ../Flowpack.RestApi
        composer config minimum-stability dev
        composer require --no-interaction --no-progress flowpack/restapi:dev-master

    - name: Run Unit tests
      run: | 
        cd ${FLOW_FOLDER} 
        bin/phpunit --colors -c Build/BuildEssentials/PhpUnit/UnitTests.xml Packages/Application/Flowpack.RestApi/Tests/Unit
      
    - name: Run Functional tests
      run: |
        cd ${FLOW_FOLDER} 
        bin/phpunit --colors -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml Packages/Application/Flowpack.RestApi/Tests/Functional/*
